services:
  mysql:
    image: mysql:8.3
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    ports:
      - '33060:3306'
    volumes:
      - .docker/mysql:/var/lib/mysql

  php:
    build:
      context: .docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:1.25
    ports:
      - '8001:80'
    volumes:
      - ./app:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  # rabbitmq:
  #   image: rabbitmq:3.12-management
  #   restart: always
  #   ports:
  #     # AMQP protocol port
  #     - "5672:5672"
  #     # HTTP management UI
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
